---

- name: Apt | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
  tags: ['apt']

- name: Apt | Install packages
  ansible.builtin.apt:
    pkg:
      - gnupg
      - apt-transport-https
      - iproute2
      - python3-psycopg2
      - iptables
    state: present
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
  tags: ['apt']
