---

- name: Upgrade /etc/hosts
  block:
    - name: Change hostname
      hostname:
        name: "{{ ansible_hostname }}"

    - name: Change hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      no_log: true
      loop:
        - { regexp: '^127\.0\.0\.1[ \t]+localhost', line: '127.0.0.1 localhost {{ ansible_hostname }}' }
  tags: ['hostname']
