---

- name: Upgrade /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: ['hostname']

- name: Disable cloud init modules update_etc_hosts
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^ - update_etc_hosts'
    line: '# - update_etc_hosts'
    owner: root
    group: root
    mode: 0644
  when: openstack is defined and openstack|bool
  tags: ['hostname']
