---

- name: KeepAlived | Install keepalived packages
  ansible.builtin.apt:
    name: "keepalived={{ keepalived_version }}"
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
  tags: ['keepalived']

- name: KeepAlived | Make sure the scripts directory exists
  ansible.builtin.file:
    dest: "{{ keepalived_scripts_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: ['keepalived']

- name: KeepAlived | Create vrrp_script haproxy_check.sh
  ansible.builtin.copy:
    src: haproxy_check.sh
    dest: "{{ keepalived_scripts_dir }}/haproxy_check.sh"
    owner: root
    group: root
    mode: 0700
  notify: restart keepalived
  tags: ['keepalived']

- name: KeepAlived | Generate conf file "/etc/keepalived/keepalived.conf"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_conf_dir }}/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived
  when: add_balancer is not defined or not add_balancer|bool
  tags: ['keepalived']

- name: KeepAlived | Add only an KeepAlived node | add_balancers.yml
  block:
    - name: "Fetch keepalived.conf conf file from {{ groups.balancers[0] }}"
      run_once: true
      ansible.builtin.fetch:
        src: "{{ keepalived_conf_dir }}/keepalived.conf"
        dest: files/keepalived.conf
        validate_checksum: true
        flat: true
      delegate_to: "{{ item }}"
      with_items:
        - "{{ groups.balancers[0]|default([]) }}"
        - "{{ groups.patroni[0]|default([]) }}"

    - name: KeepAlived | Copy keepalived.conf conf file to replica
      ansible.builtin.copy:
        src: files/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

    - name: KeepAlived | Remove keepalived.conf file from localhost
      run_once: true
      ansible.builtin.file:
        path: files/keepalived.conf
        state: absent
      delegate_to: localhost

    - name: KeepAlived | Prepare keepalived.conf conf file (replace "interface")
      ansible.builtin.lineinfile:
        path: "{{ keepalived_conf_dir }}/keepalived.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: true
      loop:
        - { regexp: '^.*interface', line: '   interface {{ vip_interface }}' }
      loop_control:
        label: "{{ item.line }}"
      notify: restart keepalived
  when: add_balancer is defined and add_balancer|bool
  tags: ['keepalived']

- meta: flush_handlers

- name: SELinux | change the keepalived_t domain to permissive
  ansible.builtin.selinux_permissive:
    name: keepalived_t
    permissive: true
  when: ansible_selinux.status is defined and
        ansible_selinux.status == 'enabled'
  ignore_errors: true
  tags: ['keepalived']

- name: KeepAlived | Install KeepAlived Exporter
  block:
    - name: KeepAlived | Download KeepAlived Exporter
      ansible.builtin.get_url:
        url: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.0/keepalived-exporter-1.3.0.linux-amd64.deb
        dest: /opt/keepalived-exporter-1.3.0.linux-amd64.deb
        mode: '0640'
        owner: root
        group: root

    - name: KeepAlived | Install KeepAlived Exporter deb package
      ansible.builtin.apt:
        deb: /opt/keepalived-exporter-1.3.0.linux-amd64.deb

    - name: KeepAlived | Install KeepAlived Exporter service
      ansible.builtin.template:
        src: keepalived-exporter.service.j2
        dest: /etc/systemd/system/keepalived-exporter.service
        owner: root
        group: root
        mode: 0644
  notify: restart keepalived-exporter
  tags: ['keepalived', 'exporter']

- meta: flush_handlers
