---

- name: Sysctl | Modify kernel parameters
  block:
    - name: Sysctl | Build a sysctl_conf dynamic variable
      ansible.builtin.set_fact:
        sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var | default([]) + (sysctl_conf[item] | default([]) | flatten(1)) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"

    - name: Sysctl | Apply new kernel parameters
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop: "{{ sysctl_conf_dynamic_var | default([]) }}"
      when: sysctl_conf_dynamic_var | default([]) | length > 0
  when: sysctl_set|bool
  tags: ['sysctl']
