---

- name: THP | Create systemd service disable-transparent-huge-pages
  ansible.builtin.copy:
    src: disable-transparent-huge-pages.service
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0644
  notify: restart disable-thp
  when: (disable_thp is defined and disable_thp|bool)
  tags: ['thp']

- meta: flush_handlers
